### PR TITLE
Ruby milestone 4 code review request

### PR DESCRIPTION
**Pull request by JelilFaisalAbudu**
- The README.md file begins with a brief introduction to the project.
- I contains a table of content, outlining the guidelines and other related matters of the project.
 
### Major Topics Discussed In The Project

- About the project.
- Tools used to build the project. - How to get a copy to your local machine.
- Project dependencies.
- How to contribute to the project.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hi @JelilFaisalAbudu and @Albertino2020 :clap: :clap:
##### Good job so far. Check my comments below :point_down:

**_README file should look professional. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone4/prof_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)). The markup you use for the readme appears._**
**_for example:_**

```
<ul>
  <h3>Features</h3>
  <li>Get a valid user input</li>
  <li>Display board after each move</li>
  <li>End game if someone wins</li>
  <li>End game if board becomes full</li>
</ul>
```
`### Built With`

**_Note: The pull request message should be about what you did in the project._**

**_fix this and submit for review._**

### _Reviewed by Temitayo Adeleke_

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by JelilFaisalAbudu** [comment]
# Code Review Request
- The README.md file begins with a brief introduction to the project.
-  I contains a table of content, outlining the guidelines and other related matters of the project.

## Major Topics Discussed In The Project.
- About the project.
- Tools used to build the project.
- How to get a copy to your local machine.
- Project dependencies.
- How to contribute to the project.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @JelilFaisalAbudu  👋

You've done really well on this.🚀
Let's fix the issue with the PR message once.👌

- [ ] As requested in the previous review, kindly edit your pull request message. To do this simply click the three dots icon at the top of the pull request. It's circled in red in the screenshot below.
[Screenshot]👇
Inkedice_screenshot_20200601-145130_LI

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Hey @JelilFaisalAbudu 
Nice try with the changes. But please edit the original PR description. Don't just comment the changes made. The previous TSE showed you how to edit the PR. Please follow his instructions and resend for another review.


### Martin Afani

**Comment by lekegitrepo** [comment]
#### Hi @JelilFaisalAbudu and @Albertino2020 :1st_place_medal: :1st_place_medal: 
#### Good job :muscle: This project is approved.

### _Reviewed by Temitayo Adeleke_.

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved.

**Pull request merged**
